package com.algorithms.sorting;

public enum MergeSortVersion {

	RECURSIVE_NAIVE_SORTER, //
	RECURSIVE_NAIVE_NLOGN_SPACE,
	RECURSIVE_NAIVE_N_SPACE,
	RECURSIVE_NAIVE_ONE_SPACE,
	RECURSIVE_POLISHED, //
	RECURSIVE_ARRAY_COPY, //
	NON_RECURSIVE;

}
