package com.algorithms.sorting;

public enum MergeSortVersion {

	RECURSIVE_SORTED_BY_INSERTION, //
	RECURSIVE_NLOGN_SPACE, //
	RECURSIVE_N_SPACE, //
	RECURSIVE_ONE_SPACE, //
	RECURSIVE_NLOGN_SPACE_DIVISION_ON_MERGE, //
	RECURSIVE_ARRAY_COPY, //
	NON_RECURSIVE_WHILE_LOOP, //
	NON_RECURSIVE_FOR_LOOP, //
	NON_RECURSIVE_PRINCETON;

}
