package com.algorithms.sorting;

public enum SortSolutionType {

	BRUTE, //
	BUBBLE_UNCHECKED_SWAPS, //
	BUBBLE_IS_SWAP_CHECKED, //
	BUBBLE_LAST_SWAP_INDEX_CHECK, //
	INSERTION, //
	SELECTION, //
	MERGE_RECURSIVE_SORTED_BY_INSERTION, //
	MERGE_RECURSIVE_NLOGN_SPACE, //
	MERGE_RECURSIVE_N_SPACE, //
	MERGE_RECURSIVE_ONE_SPACE, //
	MERGE_RECURSIVE_NLOGN_SPACE_DIVISION_ON_MERGE, //
	MERGE_RECURSIVE_ARRAY_COPY, //
	MERGE_NON_RECURSIVE_WHILE_LOOP, //
	MERGE_NON_RECURSIVE_FOR_LOOP, //
	MERGE_NON_RECURSIVE_PRINCETON, //
	QUICKSORT_INITIAL_PIVOT, //
	QUICKSORT_MIDDLE_PIVOT, //
	QUICKSORT_RANDOM_PIVOT, //
	QUICKSORT_DUAL_PIVOT;

}
