package com.algorithms.sorting;

public enum SortSolutionType {

	PLAIN, //
	BUBBLE_V1, //
	BUBBLE_V2, //
	BUBBLE_V3, //
	INSERTION, //
	SELECTION, //
	MERGE_RECURSIVE_NAIVE_SORTER, //
	MERGE_RECURSIVE_NLOGN_SPACE, //
	MERGE_RECURSIVE_N_SPACE, //
	MERGE_RECURSIVE_ONE_SPACE, //
	MERGE_RECURSIVE_POLISHED, //
	MERGE_RECURSIVE_ARRAY_COPY, //
	MERGE_NON_RECURSIVE;

}
